version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - /home/sandovallucasj/mosquitto/config:/mosquitto/config
      - /home/sandovallucasj/mosquitto/data:/mosquitto/data
      - /home/sandovallucasj/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
  
  influxdb2:
    image: influxdb:2.6
    container_name: influxdb2
    volumes:
      - /home/sandovallucasj/influxdb/data:/var/lib/influxdb2
      - /home/sandovallucasj/influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=secret-password
      - DOCKER_INFLUXDB_INIT_ORG=my-init-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-init-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret-token

